version: '3'

services:
  portfolio-api:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: portfolio-api:latest
    container_name: portfolio-api
    volumes:
      - ./:/var/www/portfolio-api:rw
    tty: true
    labels:
      - traefik.http.routers.portfolio.rule=Host(`portfolio-api.melaine-gerard.fr`)
      - traefik.http.routers.portfolio.tls=true
      - traefik.http.routers.portfolio.tls.certresolver=lets-encrypt
      - traefik.port=80
      - "traefik.enable=true"
    networks:
      - local
networks:
  local:
    external: true