name: PHPUnit

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.34
        ports:
          - 3306:3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test_database
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Create database
        env:
          DATABASE_URL: "mysql://root:password@127.0.0.1:3306/test_database?serverVersion=8.0.34"
        run: php bin/console d:d:c --no-interaction --if-not-exists --env=test
      - name: Migrate database
        env:
          DATABASE_URL: "mysql://root:password@127.0.0.1:3306/test_database?serverVersion=8.0.34"
        run: php bin/console d:m:m --no-interaction --env=test
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DATABASE_URL: "mysql://root:password@127.0.0.1:3306/test_database?serverVersion=8.0.34"
        run: vendor/bin/phpunit